"""v2_envelope_types_transaction_status

Revision ID: c7447ba16544
Revises: b2c3d4e5f6a7
Create Date: 2026-03-23 15:17:22.260746

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7447ba16544"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("envelopes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "envelope_type",
                sa.String(length=20),
                nullable=False,
                server_default="regular",
            )
        )
        batch_op.add_column(
            sa.Column(
                "period", sa.String(length=20), nullable=False, server_default="monthly"
            )
        )
        batch_op.add_column(sa.Column("target_amount", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "stop_on_target",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status", sa.String(length=20), nullable=False, server_default="real"
            )
        )
        batch_op.drop_column("virtual_linked_id")
        batch_op.drop_column("cleared")
        batch_op.drop_column("is_virtual")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_virtual", sa.BOOLEAN(), nullable=False, server_default=sa.text("0")
            )
        )
        batch_op.add_column(
            sa.Column(
                "cleared",
                sa.VARCHAR(length=20),
                nullable=False,
                server_default="uncleared",
            )
        )
        batch_op.add_column(sa.Column("virtual_linked_id", sa.INTEGER(), nullable=True))
        batch_op.drop_column("status")

    with op.batch_alter_table("envelopes", schema=None) as batch_op:
        batch_op.drop_column("stop_on_target")
        batch_op.drop_column("target_amount")
        batch_op.drop_column("period")
        batch_op.drop_column("envelope_type")

    # ### end Alembic commands ###
